name: Run example

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies and package
      run: |
        pip install -r requirements.txt
        pip install -e .

    - name: List compilers
      run: diagtest --list-compilers

    - name: Run example
      run: diagtest examples/undeclared.cpp --brief --junit-xml results/report-${{ matrix.os }}-${{ matrix.python-version }}.xml
    
    - name: Test Summary
      uses: test-summary/action@v2
      with:
        paths: "results/report-*.xml"
      if: always()